// Copyright (c) 2021 Gitpod GmbH. All rights reserved.
// Licensed under the GNU Affero General Public License (AGPL).
// See License-AGPL.txt in the project root for license information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workspace.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DownloadUrlWorkspaceRequest struct {
	OwnerId              string   `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	WorkspaceId          string   `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadUrlWorkspaceRequest) Reset()         { *m = DownloadUrlWorkspaceRequest{} }
func (m *DownloadUrlWorkspaceRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadUrlWorkspaceRequest) ProtoMessage()    {}
func (*DownloadUrlWorkspaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dac718ecaafc2333, []int{0}
}

func (m *DownloadUrlWorkspaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadUrlWorkspaceRequest.Unmarshal(m, b)
}
func (m *DownloadUrlWorkspaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadUrlWorkspaceRequest.Marshal(b, m, deterministic)
}
func (m *DownloadUrlWorkspaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadUrlWorkspaceRequest.Merge(m, src)
}
func (m *DownloadUrlWorkspaceRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadUrlWorkspaceRequest.Size(m)
}
func (m *DownloadUrlWorkspaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadUrlWorkspaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadUrlWorkspaceRequest proto.InternalMessageInfo

func (m *DownloadUrlWorkspaceRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *DownloadUrlWorkspaceRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

type DownloadUrlWorkspaceResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadUrlWorkspaceResponse) Reset()         { *m = DownloadUrlWorkspaceResponse{} }
func (m *DownloadUrlWorkspaceResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadUrlWorkspaceResponse) ProtoMessage()    {}
func (*DownloadUrlWorkspaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dac718ecaafc2333, []int{1}
}

func (m *DownloadUrlWorkspaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadUrlWorkspaceResponse.Unmarshal(m, b)
}
func (m *DownloadUrlWorkspaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadUrlWorkspaceResponse.Marshal(b, m, deterministic)
}
func (m *DownloadUrlWorkspaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadUrlWorkspaceResponse.Merge(m, src)
}
func (m *DownloadUrlWorkspaceResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadUrlWorkspaceResponse.Size(m)
}
func (m *DownloadUrlWorkspaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadUrlWorkspaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadUrlWorkspaceResponse proto.InternalMessageInfo

func (m *DownloadUrlWorkspaceResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DeleteWorkspaceRequest struct {
	OwnerId              string   `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	WorkspaceId          string   `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWorkspaceRequest) Reset()         { *m = DeleteWorkspaceRequest{} }
func (m *DeleteWorkspaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteWorkspaceRequest) ProtoMessage()    {}
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dac718ecaafc2333, []int{2}
}

func (m *DeleteWorkspaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWorkspaceRequest.Unmarshal(m, b)
}
func (m *DeleteWorkspaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWorkspaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteWorkspaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWorkspaceRequest.Merge(m, src)
}
func (m *DeleteWorkspaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteWorkspaceRequest.Size(m)
}
func (m *DeleteWorkspaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWorkspaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWorkspaceRequest proto.InternalMessageInfo

func (m *DeleteWorkspaceRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *DeleteWorkspaceRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

type DeleteWorkspaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWorkspaceResponse) Reset()         { *m = DeleteWorkspaceResponse{} }
func (m *DeleteWorkspaceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteWorkspaceResponse) ProtoMessage()    {}
func (*DeleteWorkspaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dac718ecaafc2333, []int{3}
}

func (m *DeleteWorkspaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWorkspaceResponse.Unmarshal(m, b)
}
func (m *DeleteWorkspaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWorkspaceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteWorkspaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWorkspaceResponse.Merge(m, src)
}
func (m *DeleteWorkspaceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteWorkspaceResponse.Size(m)
}
func (m *DeleteWorkspaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWorkspaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWorkspaceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DownloadUrlWorkspaceRequest)(nil), "contentservice.DownloadUrlWorkspaceRequest")
	proto.RegisterType((*DownloadUrlWorkspaceResponse)(nil), "contentservice.DownloadUrlWorkspaceResponse")
	proto.RegisterType((*DeleteWorkspaceRequest)(nil), "contentservice.DeleteWorkspaceRequest")
	proto.RegisterType((*DeleteWorkspaceResponse)(nil), "contentservice.DeleteWorkspaceResponse")
}

func init() {
	proto.RegisterFile("workspace.proto", fileDescriptor_dac718ecaafc2333)
}

var fileDescriptor_dac718ecaafc2333 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xcf, 0x2f, 0xca,
	0x2e, 0x2e, 0x48, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0xce, 0xcf,
	0x2b, 0x49, 0xcd, 0x2b, 0x29, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55, 0x8a, 0xe6, 0x92, 0x76,
	0xc9, 0x2f, 0xcf, 0xcb, 0xc9, 0x4f, 0x4c, 0x09, 0x2d, 0xca, 0x09, 0x87, 0xa9, 0x0e, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe4, 0xe2, 0xc8, 0x2f, 0xcf, 0x4b, 0x2d, 0x8a, 0xcf, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x07, 0xf3, 0x3d, 0x53, 0x84, 0x14, 0xb9, 0x78,
	0xe0, 0x86, 0x83, 0xa4, 0x99, 0xc0, 0xd2, 0xdc, 0x70, 0x31, 0xcf, 0x14, 0x25, 0x03, 0x2e, 0x19,
	0xec, 0x86, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x09, 0x70, 0x31, 0x97, 0x16, 0xe5, 0x40,
	0x0d, 0x06, 0x31, 0x95, 0xc2, 0xb8, 0xc4, 0x5c, 0x52, 0x73, 0x52, 0x4b, 0x52, 0xa9, 0xec, 0x12,
	0x49, 0x2e, 0x71, 0x0c, 0x73, 0x21, 0x8e, 0x30, 0x7a, 0xcb, 0xc8, 0x25, 0x00, 0x17, 0x0d, 0x86,
	0x04, 0x8b, 0x50, 0x31, 0x97, 0x08, 0x36, 0x97, 0x0b, 0x69, 0xeb, 0xa1, 0x86, 0x9f, 0x1e, 0x9e,
	0xc0, 0x93, 0xd2, 0x21, 0x4e, 0x31, 0xc4, 0x1d, 0x4a, 0x0c, 0x42, 0x29, 0x5c, 0xfc, 0x68, 0x8e,
	0x14, 0x52, 0xc3, 0x30, 0x02, 0x6b, 0xe8, 0x48, 0xa9, 0x13, 0x54, 0x07, 0xb3, 0xc5, 0xc9, 0x30,
	0x4a, 0x3f, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x17, 0xc4, 0x2c, 0xc8, 0x4f,
	0xd1, 0xcd, 0xcc, 0x87, 0xb2, 0xf4, 0xa1, 0xe6, 0xe8, 0x42, 0x0d, 0xd2, 0x4f, 0x2c, 0xc8, 0x4c,
	0x62, 0x03, 0xa7, 0x1d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xeb, 0x4e, 0xa5, 0x4e,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WorkspaceServiceClient is the client API for WorkspaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkspaceServiceClient interface {
	// DownloadUrlWorkspace provides a URL from where the content of a workspace can be downloaded from
	DownloadUrlWorkspace(ctx context.Context, in *DownloadUrlWorkspaceRequest, opts ...grpc.CallOption) (*DownloadUrlWorkspaceResponse, error)
	// DeleteWorkspace deletes the content of a single workspace
	DeleteWorkspace(ctx context.Context, in *DeleteWorkspaceRequest, opts ...grpc.CallOption) (*DeleteWorkspaceResponse, error)
}

type workspaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceServiceClient(cc grpc.ClientConnInterface) WorkspaceServiceClient {
	return &workspaceServiceClient{cc}
}

func (c *workspaceServiceClient) DownloadUrlWorkspace(ctx context.Context, in *DownloadUrlWorkspaceRequest, opts ...grpc.CallOption) (*DownloadUrlWorkspaceResponse, error) {
	out := new(DownloadUrlWorkspaceResponse)
	err := c.cc.Invoke(ctx, "/contentservice.WorkspaceService/DownloadUrlWorkspace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) DeleteWorkspace(ctx context.Context, in *DeleteWorkspaceRequest, opts ...grpc.CallOption) (*DeleteWorkspaceResponse, error) {
	out := new(DeleteWorkspaceResponse)
	err := c.cc.Invoke(ctx, "/contentservice.WorkspaceService/DeleteWorkspace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceServiceServer is the server API for WorkspaceService service.
type WorkspaceServiceServer interface {
	// DownloadUrlWorkspace provides a URL from where the content of a workspace can be downloaded from
	DownloadUrlWorkspace(context.Context, *DownloadUrlWorkspaceRequest) (*DownloadUrlWorkspaceResponse, error)
	// DeleteWorkspace deletes the content of a single workspace
	DeleteWorkspace(context.Context, *DeleteWorkspaceRequest) (*DeleteWorkspaceResponse, error)
}

// UnimplementedWorkspaceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWorkspaceServiceServer struct {
}

func (*UnimplementedWorkspaceServiceServer) DownloadUrlWorkspace(ctx context.Context, req *DownloadUrlWorkspaceRequest) (*DownloadUrlWorkspaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadUrlWorkspace not implemented")
}
func (*UnimplementedWorkspaceServiceServer) DeleteWorkspace(ctx context.Context, req *DeleteWorkspaceRequest) (*DeleteWorkspaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkspace not implemented")
}

func RegisterWorkspaceServiceServer(s *grpc.Server, srv WorkspaceServiceServer) {
	s.RegisterService(&_WorkspaceService_serviceDesc, srv)
}

func _WorkspaceService_DownloadUrlWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadUrlWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).DownloadUrlWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contentservice.WorkspaceService/DownloadUrlWorkspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).DownloadUrlWorkspace(ctx, req.(*DownloadUrlWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_DeleteWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).DeleteWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contentservice.WorkspaceService/DeleteWorkspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).DeleteWorkspace(ctx, req.(*DeleteWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkspaceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contentservice.WorkspaceService",
	HandlerType: (*WorkspaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DownloadUrlWorkspace",
			Handler:    _WorkspaceService_DownloadUrlWorkspace_Handler,
		},
		{
			MethodName: "DeleteWorkspace",
			Handler:    _WorkspaceService_DeleteWorkspace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workspace.proto",
}
